std_msgs/Header header

sensor_msgs/Image head_left
bool head_left_state
sensor_msgs/Image head_right
bool head_right_state
sensor_msgs/Image front_left
bool front_left_state
sensor_msgs/Image front_right
bool front_right_state
sensor_msgs/Image mid_left
bool mid_left_state
sensor_msgs/Image mid_right
bool mid_right_state
sensor_msgs/Image tail_left
bool tail_left_state
sensor_msgs/Image tail_right
bool tail_right_state

