load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_object",
    hdrs = [
        "test_object.h",
    ],
    # deps = [
        # "//modules/common:log",
    # ],
)

cpplint()
