pipeline {
  agent {
    label 'Production'
  }
  options {
    timeout(time: 3, unit: 'HOURS')
  }
  stages {
    stage('Build') {            
      steps {                
        echo 'Building'            
        sh './jenkins/build_deploy_test/scripts/build.sh'                
      }        
    }        
    stage('Package - Staging') {            
      steps {                
        echo 'Package'            
        sh './jenkins/build_deploy_test/scripts/package.sh'                
      }        
    }        
    stage('Test') {            
      steps {                
        echo 'Testing'            
        sh 'docker port jenkins_roadstar_dev | sed "s/2222[^:]*/ssh/" | sed "s/8888[^:]*/dreamview/" '
        sh './jenkins/build_deploy_test/scripts/test.sh'                
      }        
    }
    stage('Deploy - Staging') {            
      steps {                
        echo 'Deploy'            
        sh './jenkins/build_deploy_test/scripts/deploy.sh'                
      }        
    }        
  }
}
