pipeline {
  agent {
    label 'Production'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
  }
  stages {
    stage('Update') {            
      steps {                
        echo 'updating'            
        sh './jenkins/update_submodule/scripts/update.sh'                
      }        
    }        
  }
}
