OUTPUT:
    # # letnet config
    # WORK_DIR: ./workdir/lenet
    # WEIGHT_BIT_TABLE: ./workdir/lenet/weight.table
    # FEAT_BIT_TABLE: ./workdir/lenet/feat.table
    # WEIGHT_DIR: ./workdir/lenet/weight
    # BIAS_DIR: ./workdir/lenet/bias
    # FINAL_WEIGHT_DIR: ./workdir/lenet/new_weight
    # FINAL_BIAS_DIR: ./workdir/lenet/new_bias

    # resnet config
    WORK_DIR: ./workdir/resnet
    WEIGHT_BIT_TABLE: ./workdir/resnet/weight.table
    FEAT_BIT_TABLE: ./workdir/resnet/feat.table
    WEIGHT_DIR: ./workdir/resnet/weight
    BIAS_DIR: ./workdir/resnet/bias
    FINAL_WEIGHT_DIR: ./workdir/resnet/new_weight
    FINAL_BIAS_DIR: ./workdir/resnet/new_bias


SETTINGS:
    GPU: 0
    WORKER_NUM: 4 
    INTERVAL_NUM: 2048
    STATISTIC: 1
    MAX_CALI_IMG_NUM: 1 
    MAX_SHIFT: 12
    SUPPORT_DILATION: False
    MERGE_FREEZEBN: False
    CARE_OP_TYPE: ['Conv2d', 'Linear', 'Eltwise', 'Concat']
    ALL_OP_TYPE: ['Conv2d', 'Linear', 'Eltwise', 'Concat', 'MaxPool2d', 'ReLU', 'UpsamplingNearest2d', 'View', 'AvgPool2d']
    ALLOW_SAME_TID_OP_TYPE: ['ReLU', 'UpsamplingNearest2d', 'View']
    MERGE_OP_YTPE: ['Eltwise', 'Concat']
