PATH:
    DATA_PATH: ./data/
    MODEL_NET_PATH: ./model/ResNet.py
    MODEL_PATH: ./model/resnet50.pth
MODEL:
    CLASS: resnet50
    CLASS_PARAM:
    INPUT_SHAPE: 1,3,224,224
PRE_PROCESS:
    IMG: FALSE
    IMG_SET:
      MEAN: 128
      RESIZE: 22,22
      SCALE: 0.0075
    
    



