PATH:
    DATA_PATH: ./data/
    MODEL_NET_PATH: ./model/lenet.py
    MODEL_PATH: ./model/lenet.pth
    QUANTITY_MODEL_PATH: ./model/quantity_lenet.pth
MODEL:
    INPUT_SHAPE: 1,1,28,28
PRE_PROCESS:
    IMG: 1  #0:imge 1:memory 2:datalist npy 
    IMG_SET:
      MEAN: 128
      RESIZE: 22,22
      SCALE: 0.0075
    
    



